language: python
python:
  - "3.5"

env:
  global:
    - PACKAGE_NAME=wireguard-p2p

install:
  - pip3 install -r requirements.txt

script:
  - echo $TRAVIS_TAG

before_deploy:
  - pwd
  - sudo bash ./before-deploy.sh

deploy:
  api_key:
    secure: VCIi81D2jzlmxi6CvSMNZPAIBRTT5YCB6/ympYS2il2JUmleBD8i8J2mWxPPGtLzW3S5WpFgtXgjRh9YtTw8ByxeK+3CEXsTxg41q7TabjRnlr3Hc6osm5qzgYIPlLyjXdjQrCDIFyj3tcLXhiquApbzmEqTsnPc1guf0TQzJvZU6fRbdx2dOEi9cgMlBS6jgIqaEHuX+akEmUDboBDSECi8K4BKwaiTQG0094IAWZU5Der7K7oSe2GUpagp2voFxmkSHIkQJdFinWRUziwyqrs2VwnKtAKA2AAwDwK1tDmUgbEBDoGvXIr9hPJlk/50YPzdjAbIR2pHCB/22NxLP5ziuRexFsNmqH+YdV6rS06tnX/6PFLSjiksT/c2AhRGiyZqOw0Dl6gI/vqJ3SktA9oa6qDpw9GY6BHzlPGRd5i+h7BiEWJDC7iUMRVKe1OAcHdgKyag6iafmGUfQqhmOx3F0ZKVSPtgozB9bQ2FayUVG71QAFN9E9jxlDzDvvOJacU00onGjxVjKY9iwrTw4fM++lx1gqu4eWbCbwST/3Qwy7Vr3q7Dx97WOPJY/yfNpu3z4qZ/HPotglvy+BkqO1bvTS8CsDjWUdkiQ/PWEU/p80itEXVqL/zOnsrn+zr4DPfw1wYgtKD7pi+eeoqUOoCJLB8L6mpUyU5rGSEvvWk=
  on:
    tags: true
  file_glob: true
  file: $PACKAGE_NAME*.deb
  provider: releases
  skip_cleanup: true

notifications:
  email:
    on_success: never
    on_failure: change
