[package]
name = "wireguard-p2p"
version = "0.1.0"
authors = ["Manuel Schölling <manuel.schoelling@gmx.de>"]

[dependencies]
docopt = "0.8.1"
error-chain = "0.11.0"
sodiumoxide = "0.0.16"
stun3489 = "0.4.0"
base64 = "~0.6.0"
futures-await = "0.1.0"
tokio-core = "0.1"
dbus = "0.5.4"
dbus-tokio = "0.1.2"
tokio-process = "0.1.2"
rust-ini = "0.10.0"
byteorder = "1.0.0"
env_logger = "0.5.3"
log = "0.3.9"
